
using static FirstConsoleGame.Utility;

namespace FirstConsoleGame
{
	/*
	[Contents]
	If Map Clear, then door open. 
	Maps differ to their Clear function. 
	Map randomly generated by stageFactory. 
		Map...Default: Clear => { Kill every monsters }
		Map...Snake: Clear => true
	If Stage Clear, then go next stage. 



	[Warnings]
	1. Entity -> IMapDataModifier (-- DungeonGame_Map
		IMapDataModifier has many authorities. 
	
	2. MapFactory needs one-by-one function to each specific map 
		It'll need more and more functions by adding new spacific map. 
		It means that modifications occur often!!
		...would it be Decorated?
	
	3. IEntity is exist. But not using well

	4. Factories are not just factorying
		They create something, and HAS something!!


	[To do]
	1. Character animations
	2. Sound
	3. Title, Options-KeySet?, GameOver
	4. 

	[Abstracts] Entity, RenderBox
	[Interfaces] IEntity, IMapDataModifier, IRenderable, 
	[Structs] MyVector, Square
	[Enum] DirIndex
	
	 */

	internal class Program
	{
		// ------------- Main
		static void Main(string[] args)
		{
			Console.CursorVisible = false;
			Console.SetWindowSize(MAX_BUFFER_WIDTH + 2, MAX_BUFFER_HEIGHT + 2);
			DungeonGame game = DungeonGame.GetInstance();
			game.Play();

			return;
		}
	}
}
