using Microsoft.Win32.SafeHandles;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static FirstConsoleGame.Program;
using static System.Runtime.InteropServices.JavaScript.JSType;


namespace FirstConsoleGame
{
	/*
	[Contents]
	If Map Clear, then door open. 
	Maps differ to their Clear function. 
	Map randomly generated by stageFactory. 
		Map...Default: Clear => { Kill every monsters }
		Map...Snake: Clear => true
	If Stage Clear, then go next stage. 



	[Warnings]
	1. Entity -> IMapDataModifier (-- DungeonGame_Map
		IMapDataModifier has many authorities. 
	
	2. MapFactory needs one-by-one function to each specific map 
		It'll need more and more functions by adding new spacific map. 
		It means that modifications occur often!!
		...would it be Decorated?
	
	3. IEntity is exist. But not using well

	4. Factories are not just factorying
		They create something, and HAS something!!


	[To do]
	1. Character animations
	2. Sound
	3. Title, Options-KeySet?, GameOver
	4. 

	[Abstracts] Entity, RenderBox
	[Interfaces] IEntity, IMapDataModifier, IRenderable, 
	[Structs] MyVector, Square
	[Enum] DirIndex
	
	 */

	internal class Program
	{
		// ------------- Globals
		const char EMPTY_SYMBOL = ' ';
		const char FENCE_SYMBOL = '#';

		const int MAX_BUFFER_HEIGHT = 50;
		const int MAX_BUFFER_WIDTH = 200;

		static Random rand = new Random((int)DateTime.Now.Ticks);

		// ------------- Struct & enum
		public struct MyVector
		{
			public int x;
			public int y;
			public MyVector(int x, int y)
			{
				this.x = x;
				this.y = y;
			}
			public (int, int) GetTuple()
			{
				return (x, y);
			}
			public bool IsOutOfSquare(MyVector v)
			{
				return v.x < 0 || v.x > this.x - 1 || v.y < 0 || v.y > this.y - 1;
			}
			public static MyVector operator +(MyVector v1, MyVector v2)
			{
				return new MyVector(v1.x + v2.x, v1.y + v2.y);
			}
		}
		public struct Square
		{
			public MyVector pos;
			public MyVector size;
			public Square(int x, int y, int w, int h)
			{
				pos = new MyVector(x, y);
				size.x = w;
				size.y = h;
			}
			public bool IsOutOfSquare(MyVector v)
			{
				return v.x < this.pos.x || v.x > this.pos.x + size.x - 1 || v.y < this.pos.y || v.y > this.pos.y + size.y - 1;
			}
		}
		public enum DirIndex
		{
			Left = 0,
			Right,
			Up,
			Down,
		}


		// ------------- Big Game Classes 
		public class DungeonGame
		{
			private static DungeonGame instance;
			private DungeonGame_Renderer renderer;
			private DungeonGame_StageFactory stageManager;
			private DungeonGame_Map curMap;
			private Player player;

			private int curStage = 1;
			private string msg = "Welcome to my dungeon game! Input your move and defeat every monster, then run out to doors!";

			// -----
			private DungeonGame()
			{
				Init();
			}
			public static DungeonGame GetInstance()
			{
				if (instance == null)
				{
					instance = new DungeonGame();
				}

				return instance;
			}
			public void Play()
			{
				bool isRunning = true;
				while (isRunning)
				{
					isRunning = Update();
				}
			}

			// -----
			public void Init()
			{
				player = (Player)EntityManager.GetInstance().GetNewInstance<Player>(new MyVector(1, 1));

				stageManager = DungeonGame_StageFactory.GetInstance();
				renderer = DungeonGame_Renderer.GetInstance(stageManager.MaxMapSize);

				SetNewStage();

				renderer.Draw(curMap, curStage, msg, player.MaxHp, player.Hp);
			}
			private void SetNewStage()
			{
				stageManager.SetNewStage(player);
				SetCurMap(stageManager.GetMap(stageManager.StartPos), DirIndex.Right);
				renderer.UpdateNewStage();
			}
			private void SetCurMap(DungeonGame_Map map, DirIndex dir)
			{
				curMap = map;
				curMap.SetPlayerPosOnNewMap(player, dir);
				curMap.UpdateMapData();
				Entity.map = curMap;
			}
			private bool Update()
			{
				curMap.Update();

				// --- Manage Input
				char dir = Utility.InputSingleChar();
				if (dir == 'Q') return false;

				// --- Get Next Move. 
				MyVector tomove = player.GetMove(dir, curMap.size);
				MyVector deltaMove = new MyVector(tomove.x - player.pos.x, tomove.y - player.pos.y);

				IEntity targetEntity = curMap.GetEntity(tomove.x, tomove.y);
				msg = targetEntity.OnPlayerEnter();

				if (targetEntity is Door && curMap.IsClear())
				{
					curMap.SetNewEntity<EmptyEntity>(player.pos);
					SetCurMap(curMap.GetDoor(Utility.charToDirIndex[dir]).GetTargetMap(), Utility.charToDirIndex[dir]);

					msg = "Next Map!!";
				}
				if(targetEntity is NextStageBicon && stageManager.IsClear())
				{
					SetNewStage();
					msg = "Next Stage!!";
					curStage++;
				}

				renderer.Draw(curMap, curStage, msg, player.MaxHp, player.Hp);

				return true;
			}
		}
		public class DungeonGame_StageFactory
		{
			/*
				최소 2개~ 최대 WIDTH*HEIGHT개의 맵을 생성하여 Grid에 저장
				
				1개는 StartMap 포함
				1개는 EndMap 포함
				위 두 특수 맵은 MapFactory에서 각각 메소드 delegate(예정)
				
				시작맵 -> 끝맵의 최단 경로 생성(돌아가지 않는 경로)

				
				남은 맵은 경로 주위에 배치(예정)
					사이드 맵(Sidemap)
						특수한 맵 배치(보너스 맵, 상점 등)
					BFS로 depth 커지지 않게 
				

			 */


			private static DungeonGame_StageFactory instance;
			private DungeonGame_MapFactory mapFactory;
			public const int GRID_WIDTH = 7;
			public const int GRID_HEIGHT = 7;

			private DungeonGame_Map[,] mapGrid = new DungeonGame_Map[GRID_HEIGHT, GRID_WIDTH];
			private MyVector gridSize = new MyVector(GRID_WIDTH, GRID_HEIGHT);

			private MyVector startPos; 
			public MyVector StartPos { get => startPos; }

			private MyVector endPos; 
			public MyVector EndPos { get => endPos; }

			private MyVector maxMapSize; 
			public MyVector MaxMapSize { get => maxMapSize; }

			private MyVector minMapSize;
			public MyVector MinMapSize { get => minMapSize; }
			public delegate bool ClearChecker();
			public ClearChecker IsClear;
			// -----
			private DungeonGame_StageFactory()
			{
				mapFactory = DungeonGame_MapFactory.GetInstance();
				// never bigger than (MAX_BUF_WIDTH - 5, MAX_BUF_HEIGHT - 3)????????????????? over flow
				maxMapSize = new MyVector(60, MAX_BUFFER_HEIGHT - 5);
				maxMapSize.x = Math.Min(maxMapSize.x, MAX_BUFFER_WIDTH - 20);
				maxMapSize.y = Math.Min(maxMapSize.y, MAX_BUFFER_HEIGHT - 5);

				// never smaller than (4, 4). 
				minMapSize = new MyVector(7, 7);
				minMapSize.x = Math.Max(minMapSize.x, 4);
				minMapSize.y = Math.Max(minMapSize.y, 4);
			}
			public static DungeonGame_StageFactory GetInstance()
			{
				if (instance == null)
					instance = new DungeonGame_StageFactory();
				return instance;
			}

			// -----
			public DungeonGame_Map GetMap(MyVector v) { return mapGrid[v.y, v.x]; }
			private MyVector GetRandMapSize()
			{
				return new MyVector(
						minMapSize.x + rand.Next() % (maxMapSize.x - minMapSize.x),
						minMapSize.y + rand.Next() % (maxMapSize.y - minMapSize.y));
			}
			private int GetRandRoomNum(int min, int max)
			{
				if (min < max)
					return Math.Max(Math.Min(rand.Next() % (max - min) + min, GRID_HEIGHT*GRID_WIDTH), 3);
				
				return 3;
			}
			private (MyVector, MyVector, HashSet<MyVector>, int) GetNewMapPath()
			{
				int roomNum = GetRandRoomNum(3, 7);
				MyVector startRoomPos = new MyVector(rand.Next() % GRID_WIDTH, rand.Next() % GRID_HEIGHT);

				// Returns min distance between two room pos. 
				Func<MyVector, MyVector, int> GetDistance = (MyVector v1, MyVector v2) => Math.Abs(v2.x - v1.x) + Math.Abs(v2.y - v1.y);

				// endRoomPosList has roomPos, which can be endRoom. 
				List<MyVector> endRoomPosList = new List<MyVector>();
				for (int r = 0; r < GRID_HEIGHT; r++)
				{
					for (int c = 0; c < GRID_WIDTH; c++)
					{
						int dist = GetDistance(startRoomPos, new MyVector(c, r));
						if (dist > 0 && dist < roomNum)
						{
							endRoomPosList.Add(new MyVector(c, r));
						}
					}
				}
				MyVector endRoomPos = endRoomPosList[rand.Next() % endRoomPosList.Count];
				roomNum -= GetDistance(endRoomPos, startRoomPos) + 1;


				// Set start~end map exclusive(main path maps)
				HashSet<MyVector> mainPaths = new HashSet<MyVector>();
				MyVector pos = startRoomPos;
				while (GetDistance(endRoomPos, pos) > 0)
				{
					mainPaths.Add(pos);
					MyVector cardinal_8_dir = new MyVector(endRoomPos.x - pos.x, endRoomPos.y - pos.y);
					if (cardinal_8_dir.x == 0)
						pos.y += cardinal_8_dir.y > 0 ? 1 : -1;
					else if (cardinal_8_dir.y == 0)
						pos.x += cardinal_8_dir.x > 0 ? 1 : -1;
					else
					{
						if (rand.Next() % 2 == 0) pos.x += cardinal_8_dir.x > 0 ? 1 : -1;
						else pos.y += cardinal_8_dir.y > 0 ? 1 : -1;
					}
				}
				mainPaths.Remove(startRoomPos);  // deque start pos

				// set side rooms. Not implemented
				MyVector boundary = new MyVector(GRID_WIDTH, GRID_HEIGHT);
				MyVector[] deltaPos = { new MyVector(1, 0), new MyVector(-1, 0), new MyVector(0, 1), new MyVector(0, -1) };

				return (startRoomPos, endRoomPos, mainPaths, roomNum);
			}
			public void SetNewStage(Player player)
			{
				(startPos, endPos, HashSet<MyVector> mainPaths, int roomNum) = GetNewMapPath();

				mapGrid = new DungeonGame_Map[GRID_HEIGHT, GRID_WIDTH];

				foreach (var pos in mainPaths)
				{
					mapGrid[pos.y, pos.x] = mapFactory.GetEmptyMap(GetRandMapSize(), pos);
				}
				mapGrid[startPos.y, startPos.x] = mapFactory.GetEmptyMap(minMapSize, startPos);
				mapGrid[endPos.y, endPos.x] = mapFactory.GetEmptyMap(maxMapSize, endPos);

				mainPaths.Add(startPos);
				mainPaths.Add(endPos);

				while (roomNum > 0)
				{
					int idx = rand.Next() % mainPaths.Count;
					MyVector crosRoadPos = mainPaths.ElementAt(idx);
					MyVector sidemapPos;
					
					sidemapPos = crosRoadPos + Utility.dirToDeltaPos[Utility.intToDirIndex[rand.Next()%4]];

					if (gridSize.IsOutOfSquare(sidemapPos) == false && mainPaths.Contains(sidemapPos) == false)
					{
						mainPaths.Add(sidemapPos);
						mapGrid[sidemapPos.y, sidemapPos.x] = mapFactory.GetEmptyMap(GetRandMapSize(), sidemapPos);
						roomNum--;
					}
				}

				foreach (var pos in mainPaths)
				{
					DungeonGame_Map curmap = mapGrid[pos.y, pos.x];
					foreach (DirIndex dir in Enum.GetValues<DirIndex>())
					{
						MyVector nearbyPos = pos + Utility.dirToDeltaPos[dir];
						if (gridSize.IsOutOfSquare(nearbyPos)) continue;
						DungeonGame_Map targetmap = mapGrid[nearbyPos.y, nearbyPos.x];
						if (targetmap != null)
						{
							curmap.SetDoorAndConnectTo(dir, targetmap);
						}
					}

					if (pos.x == startPos.x && pos.y == startPos.y)
						mapFactory.FillUpMap_Start(curmap);
					else if (pos.x == endPos.x && pos.y == endPos.y)
						mapFactory.FillUpMap_End(curmap);
					else
					{
						int randvar = rand.Next() % mapFactory.GetMapTasks.Count;
						mapFactory.GetMapTasks[randvar](curmap);
					}
				}

				IsClear = () =>
				{
					bool flag = true;
					for (int i = 0; i < gridSize.y; i++)
					{
						for (int j = 0; j < gridSize.x; j++)
						{
							if (mapGrid[i, j] == null) continue;

							flag = flag && mapGrid[i, j].IsClear();
						}
					}
					return flag;
				};
			}
		}
		public class DungeonGame_MapFactory
		{

			// ----- Singleton + Constructor
			private static DungeonGame_MapFactory instance;
			EntityManager entityManager;
			private DungeonGame_MapFactory() 
			{
				entityManager = EntityManager.GetInstance();
				GetMapTasks = new List<GetMapDelegate>();
				//GetMapTasks.Add(FillUpMap_Default);
				GetMapTasks.Add(FillUpMap_Snake);
				//GetMapTasks.Add(FillUpMap_SnakeGrowUp);
				//GetMapTasks.Add(FillUpMap_BigSnake);
			}
			public static DungeonGame_MapFactory GetInstance()
			{
				if (instance == null)
				{
					instance = new DungeonGame_MapFactory();
				}

				return instance;
			}

			public delegate void GetMapDelegate(DungeonGame_Map map);
			public List<GetMapDelegate> GetMapTasks;

			// -----
			public DungeonGame_Map GetEmptyMap(MyVector mapSize, MyVector gridPos)
			{
				DungeonGame_Map map = new DungeonGame_Map(mapSize, gridPos, difficulty: 1f);

				map.SetEmptyMap();

				return map;
			}
	
			public void FillUpMap_Default(DungeonGame_Map map)
			{
				HashSet<(int, int)> monsterPos = new HashSet<(int, int)>();
				List<MyVector> endPos = new List<MyVector>();
				GetRandomEmptyPos(map, ref monsterPos, map.InitMonsterNum);
				foreach (var pos in monsterPos)
				{
					map.SetNewEntity<Monster>(new MyVector(pos.Item1, pos.Item2));
					endPos.Add(new MyVector(pos.Item1, pos.Item2));
				}
				map.IsClear = () => map.GetMapData()["monster_cnt"] == 0;

				foreach(var pos in map.GetDoorCardinalPos())
				{
					if(map.GetEntity(pos.x, pos.y) is Door)
						endPos.Add(pos);
				}

				SetRandomFences(map, map.GetDoorCardinalPos(), endPos.ToArray(), map.InitFenceNum);

				map.UpdateMapData();
			}
			public void FillUpMap_SnakeGrowUp(DungeonGame_Map map)
			{
				HashSet<(int, int)> monsterPos = new HashSet<(int, int)>();
				List<MyVector> endPos = new List<MyVector>();
				GetRandomEmptyPos(map, ref monsterPos, map.InitMonsterNum);
				foreach (var pos in monsterPos)
				{
					if(rand.Next()%3 == 0)
						map.SetNewEntity<SnakeBaby>(new MyVector(pos.Item1, pos.Item2));
					else
						map.SetNewEntity<Monster>(new MyVector(pos.Item1, pos.Item2));
					endPos.Add(new MyVector(pos.Item1, pos.Item2));
				}
				map.IsClear = () => map.GetMapData()["monster_cnt"] == 0;

				foreach (var pos in map.GetDoorCardinalPos())
				{
					if (map.GetEntity(pos.x, pos.y) is Door)
						endPos.Add(pos);
				}

				SetRandomFences(map, map.GetDoorCardinalPos(), endPos.ToArray(), map.InitFenceNum);

				map.UpdateMapData();
			}
			public void FillUpMap_Snake(DungeonGame_Map map)
			{
				HashSet<(int, int)> monsterPos = new HashSet<(int, int)>();
				GetRandomEmptyPos(map, ref monsterPos, map.InitMonsterNum);
				foreach (var pos in monsterPos)
				{
					map.SetNewEntity<Snake_Head>(new MyVector(pos.Item1, pos.Item2));
				}
				map.IsClear = () => false;	// Snake monster gives u clear token. 

				map.UpdateMapData();
			}
			public void FillUpMap_BigSnake(DungeonGame_Map map)
			{
				HashSet<(int, int)> monsterPos = new HashSet<(int, int)>();
				GetRandomEmptyPos(map, ref monsterPos, 1);
				foreach (var pos in monsterPos)
				{
					map.SetNewEntity<BigSnake_Head>(new MyVector(pos.Item1, pos.Item2));
				}
				map.IsClear = () => false;  // Snake monster gives u clear token. 

				map.UpdateMapData();
			}
			public void FillUpMap_Start(DungeonGame_Map map)
			{
				map.IsClear = () => true;
				HashSet<(int, int)> healingPotionPos = new HashSet<(int, int)>();
				GetRandomEmptyPos(map, ref healingPotionPos, 1);
				foreach (var pos in healingPotionPos)
				{
					map.SetNewEntity<HealingPotion>(new MyVector(pos.Item1, pos.Item2));
				}

				map.UpdateMapData();
			}
			public void FillUpMap_End(DungeonGame_Map map)
			{
				map.IsClear = () => true;
				HashSet<(int, int)> healingPotionPos = new HashSet<(int, int)>();
				GetRandomEmptyPos(map, ref healingPotionPos, 2);
				foreach (var pos in healingPotionPos)
				{
					map.SetNewEntity<HealingPotion>(new MyVector(pos.Item1, pos.Item2));
				}

				HashSet<(int, int)> NextStageBiconPos = new HashSet<(int, int)>();
				GetRandomEmptyPos(map, ref NextStageBiconPos, 1);
				foreach (var pos in NextStageBiconPos)
				{
					map.SetNewEntity<NextStageBicon>(new MyVector(pos.Item1, pos.Item2));
				}

				map.UpdateMapData();
			}
			
			/// <summary>
			/// Set Fences amount of many, on map that can have startPos[] and endPos[]. 
			/// startPos[] can be... 
			///		...Doors are set on the middle of each walls...4 doors for maximum. 
			/// endPos[] can be...
			///		...Monsters that must be killed to escape room. 
			///			...But SnakeMonsters dont need to be killed to escape room. So they are not contained in endPos[]
			///		...Doors since player have to reach here. 
			///	
			/// [How This Method work]
			///	Get Random Empty Space Positions. Fill that positions with Fence. 
			///	Then, Get All the reachable positions. this positions can be reached even if player dont pass through fences. 
			/// Check if reachable positions contain all the endPos. 
			///		if true, Place Fence Entity.
			///		else, do above tasks again.  
			/// 
			/// </summary>
			/// <param name="map"></param>
			/// <param name="startPos"></param>
			/// <param name="endPos"></param>
			/// <param name="many"></param>
			private void SetRandomFences(DungeonGame_Map map, MyVector[] startPos, MyVector[] endPos, int many)
			{
				HashSet<(int, int)> notAllowedPos = new HashSet<(int, int)>();  // fence positions
				HashSet<(int, int)> reachables = new HashSet<(int, int)>();     // endPositions must be subset of this.
				bool flag = false;
				do
				{
					flag = true;
					notAllowedPos.Clear();
					reachables.Clear();
					GetRandomEmptyPos(map, ref notAllowedPos, many);
					GetReachables(map, ref reachables, startPos, [FENCE_SYMBOL], notAllowedPos);
					foreach (var pos in endPos)
					{
						flag = flag && reachables.Contains(pos.GetTuple());
						if (flag == false)
							break;
					}
				} while (flag == false);

				foreach (var pos in notAllowedPos)
				{
					Fence entity = (Fence)entityManager.GetNewInstance<Fence>(new MyVector(pos.Item1, pos.Item2));
					map.SetEntity(entity, entity.pos);
				}
			}
			private HashSet<(int, int)> GetReachables(DungeonGame_Map map, ref HashSet<(int, int)> visited, MyVector[] starts, HashSet<char> notAllowedSymbols, HashSet<(int, int)> notAllowedPos)
			{

				(int, int)[] dp = { (0, 1), (0, -1), (1, 0), (-1, 0) };

				HashSet<(int, int)>[] subVisited = new HashSet<(int, int)>[starts.Length];
				for(int i = 0; i < starts.Length; i++)
				{
					Queue<(int, int)> que = new Queue<(int, int)>();
					subVisited[i] = new HashSet<(int, int)>();
					subVisited[i].Add((starts[i].x, starts[i].y));
					que.Enqueue((starts[i].x, starts[i].y));
					do
					{
						(int x, int y) = que.Dequeue();
						for (int j = 0; j < 4; j++)
						{
							(int dx, int dy) = (x + dp[j].Item1, y + dp[j].Item2);
							if (dx < 0 || dy < 0 || dx >= map.size.x || dy >= map.size.y) continue;
							if (subVisited[i].Contains((dx, dy)) || notAllowedPos.Contains((dx, dy)) || notAllowedSymbols.Contains(map.GetEntity(dx, dy).symbol))
								continue;

							que.Enqueue((dx, dy));
							subVisited[i].Add((dx, dy));
						}
					} while (que.Count > 0);
				}
				visited.UnionWith(subVisited[0]);
				for(int i = 1; i < starts.Length; i++)
				{
					visited.IntersectWith(subVisited[i]);
				}

				return visited;
			}
			private void GetRandomEmptyPos(DungeonGame_Map map, ref HashSet<(int, int)> visited, int cnt)
			{
				while (cnt > 0)
				{
					int x = rand.Next() % map.size.x;
					int y = rand.Next() % map.size.y;

					// cannot overlap. char c only set to ' ': empty space. 
					if (map.GetEntity(x, y) is EmptyEntity)
					{
						cnt--;
						visited.Add((x, y));
					}
				}
			}
		}
		public interface IMapDataModifier
		{
			// Too many Authority
			public void SetEntity(Entity entity, MyVector pos);
			public void SetNewEntity<T>(MyVector pos) where T : Entity, new();
			public Entity GetEntity(int x, int y);
			public Dictionary<string, int> GetMapData();
			public void Swap(MyVector v1, MyVector v2);
			public MyVector GetSize();
			public void UpdateMapData();
			public void SetClear(bool value);
		}
		public class DungeonGame_Map : IMapDataModifier
		{
			/* Too many roles...

			*/
			EntityManager entityManager;

			
			private MyVector gridPos; // pos of Stage grid. init at MapFactory.GetEmptyMap 
			public MyVector GridPos { get => gridPos; }

			// ----- map data
			private Entity[,] buf;
			public MyVector size;

			Dictionary<string, int> mapData = new Dictionary<string, int>();

			// ----- difficulty
			public float difficulty = 1f;
			private const float monster_rate = 0.04f;
			private const float fence_rate = 0.17f;
			public int InitMonsterNum { get => (int)((size.x - 1) * (size.y - 1) * monster_rate * difficulty); }
			public int InitFenceNum { get => (int)((size.x - 1) * (size.y - 1) * fence_rate * difficulty); }

			// -----
			public delegate bool ClearChecker();
			public ClearChecker IsClear;

			// -----
			public DungeonGame_Map(MyVector size, MyVector gridPos, float difficulty)
			{
				this.size = new MyVector(size.x, size.y);
				this.gridPos = gridPos;
				this.difficulty = difficulty;

				buf = new Entity[size.y, size.x];
				entityManager = EntityManager.GetInstance();
			}

			// ----- GET / SET, Interface Implements 
			public void SetClear(bool value)
			{
				IsClear = () => value;
			}
			public void SetEntity(Entity entity, MyVector pos)
			{
				buf[pos.y, pos.x] = entity;
			}
			public void SetNewEntity<T>(MyVector pos) where T : Entity, new()
			{
				T entity = (T)entityManager.GetNewInstance<T>(pos);
				SetEntity(entity, pos);
			}
			public Entity GetEntity(int x, int y)
			{
				return buf[y, x];
			}
			public MyVector GetSize()
			{
				return size;
			}
			public Dictionary<string, int> GetMapData()
			{
				return mapData;
			}
			public void Swap(MyVector v1, MyVector v2)
			{
				(buf[v1.y, v1.x], buf[v2.y, v2.x]) = (buf[v2.y, v2.x], buf[v1.y, v1.x]);
				buf[v1.y, v1.x].pos = v1;
				buf[v2.y, v2.x].pos = v2;
			}
			public void UpdateMapData()
			{
				mapData.Clear();
				mapData.Add("width", size.x);
				mapData.Add("height", size.y);

				int monster_cnt = 0;
				for (int r = 0; r < size.y; r++)
				{
					for (int c = 0; c < size.x; c++)
					{
						if (buf[r, c] is Monster)
						{
							mapData.Add("monster_" + monster_cnt + "_x", c);
							mapData.Add("monster_" + monster_cnt + "_y", r);
							monster_cnt++;
						}
						else if (buf[r, c] is Player)
						{
							mapData.Add("player_x", c);
							mapData.Add("player_y", r);
						}
					}
				}
				mapData.Add("monster_cnt", monster_cnt);
			}

			// -----
			public void Update()
			{
				foreach (var entity in buf)
				{
					entity.IsUpdatedOnCurFrame = false;
				}

				foreach (var entity in buf)
				{
					if (entity.IsUpdatedOnCurFrame == false)
					{
						entity.IsUpdatedOnCurFrame = true;
						entity.Update();
					}
				}
			}
			public MyVector[] GetDoorCardinalPos()
			{
				MyVector[] doorPosDatas = new MyVector[4];
				doorPosDatas[(int)DirIndex.Left] = new MyVector(0, size.y / 2);
				doorPosDatas[(int)DirIndex.Right] = new MyVector(size.x - 1, size.y / 2);
				doorPosDatas[(int)DirIndex.Up] = new MyVector(size.x / 2, 0);
				doorPosDatas[(int)DirIndex.Down] = new MyVector(size.x / 2, size.y - 1);

				return doorPosDatas;
			}
			public Door GetDoor(DirIndex dir)
			{
				MyVector pos = GetDoorCardinalPos()[(int)dir];
				return (Door)GetEntity(pos.x, pos.y);
			}
			public void SetDoorAndConnectTo(DirIndex dir, DungeonGame_Map map)
			{
				MyVector[] doorPosDatas = GetDoorCardinalPos();

				MyVector pos = doorPosDatas[(int)dir];
				SetNewEntity<Door>(pos);
				((Door)GetEntity(pos.x, pos.y)).ConnectTo(map);
			}
			
			public void SetEmptyMap()
			{
				for (int i = 0; i < size.y; i++)
				{
					for (int j = 0; j < size.x; j++)
					{
						SetNewEntity<EmptyEntity>(new MyVector(j, i));

						if (i == 0 || i == size.y - 1) SetNewEntity<Fence>(new MyVector(j, i));
						else if (j == 0 || j == size.x - 1) SetNewEntity<Fence>(new MyVector(j, i));
					}
				}
			}
			public void SetPlayerPosOnNewMap(Player player, DirIndex lastMoveDir)
			{
				//----------- set player position by last move, add door player last passed-through
				player.pos = new MyVector(size.x / 2, size.y / 2);
				
				switch (lastMoveDir)
				{
					case DirIndex.Left: player.pos.x = size.x - 2; break;
					case DirIndex.Right: player.pos.x = 1; break;
					case DirIndex.Up: player.pos.y = size.y - 2; break;
					case DirIndex.Down: player.pos.y = 1; break;
				}
				buf[player.pos.y, player.pos.x] = player;
			}
			
		}

		// ------------- Renderers
		public interface IRenderable
		{
			public void Render(char[,] buf);
		}
		public abstract class RenderBox : IRenderable
		{
			public MyVector Size { get => size; }
			protected MyVector size { get; }

			public MyVector Margin { get => margin; }

			protected MyVector margin;

			public char[,] buf;

			protected RenderBox(MyVector size)
			{
				this.buf = new char[size.y, size.x];
				this.margin = new MyVector(0, 0);
				this.size = size;
				Init();
			}
			protected RenderBox(MyVector margin, MyVector size)
			{
				this.buf = new char[size.y, size.x];
				this.margin = margin;
				this.size = size;
				Init();
			}
			public abstract void Init();
			public virtual void Render(char[,] parentbuf)
			{
				for (int r = 0; r < size.y; r++)
				{
					for (int c = 0; c < size.x; c++)
					{
						int globalx = c;
						int globaly = r;
						parentbuf[r + margin.y, c + margin.x] = buf[r, c];
					}
				}

				for (int r = 1; r < size.y - 1; r++)
				{
					for (int c = 1; c < size.x - 1; c++)
					{
						buf[r, c] = ' ';
					}
				}
			}
			protected void DrawBorder(string str)
			{
				for (int i = 0; i < size.y; i++)
				{
					for (int j = 0; j < size.x; j++)
					{
						if (i == 0 || i == size.y - 1)
							buf[i, j] = '─';
						else if (j == 0 || j == size.x - 1)
							buf[i, j] = '│';
						else
							buf[i, j] = ' ';
					}
				}
				buf[0, 0] = '┌';
				buf[size.y - 1, 0] = '└';
				buf[0, size.x - 1] = '┐';
				buf[size.y - 1, size.x - 1] = '┘';

				MyVector pos = new MyVector(size.x / 2 - str.Length / 2, 0);
				for (int i = 0; i < str.Length; i++)
					buf[pos.y, pos.x + i] = str[i];
			}
		}
		public class MapRenderBox : RenderBox
		{
			// Todo: 드로우 명령을 RenderBox와 호환 가능하도록 리팩토링. 현재 상위 Renderer에서 예외처리되고있음
			public MyVector padding;
			private MyVector curMapSize;
			private int curStageNum;

			public MapRenderBox(MyVector size) : base(size) { }
			public MapRenderBox(MyVector margin, MyVector size) : base(margin, size) { }
			public override void Init()
			{
				DrawBorder($" [Stage {curStageNum}]");
			}
			public void Update(DungeonGame_Map map, int stageNum)
			{
				this.curStageNum = stageNum;
				padding = new MyVector((size.x - map.size.x) / 2, (size.y - map.size.y) / 2);
				curMapSize = map.size;

				char[,] tmpbuf = new char[map.size.y, map.size.x]; 
				for (int r = 0; r < map.size.y; r++)
				{
					for (int c = 0; c < map.size.x; c++)
					{
						map.GetEntity(c, r).Render(tmpbuf);

						buf[r + padding.y, c + padding.x] = tmpbuf[r, c];
					}
				}
			}
		}
		public class MsgRenderBox : RenderBox
		{
			public string msg = "";
			public MsgRenderBox(MyVector size) : base(size) { }
			public MsgRenderBox(MyVector margin, MyVector size) : base(margin, size) { }

			public override void Init() { DrawBorder(" [Text]"); }
			public void Update(string msg)
			{
				this.msg = msg;
			}
			public override void Render(char[,] parentbuf)
			{
				int padding_x = 3;  //padding include outliner
				int padding_y = 2;

				int msg_curx = padding_x;
				int msg_cury = padding_y;

				int msg_ex = size.x - 2 - padding_x;
				int msg_ey = size.y - 2 - padding_y;

				int it = 0; // msg iterator

				// clear
				for (int local_y = 1; local_y < size.y - 1; local_y++)
				{
					for (int local_x = 1; local_x < size.x - 1; local_x++)
					{
						buf[local_y, local_x] = EMPTY_SYMBOL;
					}
				}

				// print msg
				for (int local_y = 0; local_y < size.y; local_y++)
				{
					for (int local_x = 0; local_x < size.x; local_x++)
					{
						int global_x = local_x + margin.x;
						int global_y = local_y + margin.y;
						if (local_x == msg_curx && local_y == msg_cury && it < msg.Length)
						{
							buf[local_y, local_x] = msg[it++];
							msg_curx++;
							if (msg_curx > msg_ex)
							{
								msg_curx = padding_x;
								msg_cury++;
							}
						}
						parentbuf[global_y, global_x] = buf[local_y, local_x];
					}
				}
			}

		}
		public class MinimapRenderBox : RenderBox
		{
			private MyVector curMapPos;
			private List<MyVector> mapPosList;
			public MinimapRenderBox(MyVector size) : base(size) { }
			public MinimapRenderBox(MyVector margin, MyVector size) : base(margin, size) { }

			public override void Init()
			{
				var factory = DungeonGame_StageFactory.GetInstance();
				mapPosList = new List<MyVector>();
				for(int r = 0; r < DungeonGame_StageFactory.GRID_HEIGHT; r++)
				{
					for(int c = 0; c < DungeonGame_StageFactory.GRID_WIDTH; c++)
					{
						var pos = new MyVector(c, r);
						var map = factory.GetMap(pos);
						if (map != null)
						{
							mapPosList.Add(pos);
						}
					}
				}
				DrawBorder(" [Mini Map]");
			}
			public void Update(DungeonGame_Map curmap)
			{
				curMapPos = curmap.GridPos;
			}
			public override void Render(char[,] parentbuf)
			{
				// clear
				for (int local_y = 1; local_y < size.y - 1; local_y++)
				{
					for (int local_x = 1; local_x < size.x - 1; local_x++)
					{
						buf[local_y, local_x] = EMPTY_SYMBOL;
					}
				}

				MyVector center = new MyVector(size.x / 2, size.y / 2);
				Square drawboxSquare = new Square(1, 1, size.x - 2, size.y - 2);
				char[,] localMapBorderChar =
				{
					{'┌','─','┐'},
					{'│',' ','│'},
					{'└','─','┘'},
				};

				int zoom = 3;
				foreach(var pos in mapPosList)
				{
					MyVector zoomed = new MyVector((pos.x - curMapPos.x) * zoom, (pos.y - curMapPos.y) * zoom);
					MyVector localPos = center + zoomed;
					for (int i = 0; i < zoom; i++)
					{
						for (int j = 0; j < zoom; j++)
						{
							MyVector tmp = localPos + new MyVector(j - zoom/2, i - zoom/2);

							char _c = localMapBorderChar[i, j];	// works properly only where zoom == 3;

							if (drawboxSquare.IsOutOfSquare(tmp) == false)
								buf[tmp.y, tmp.x] = _c;
						}
					}
				}
				buf[size.y / 2, size.x / 2] = '┼';
				

				// print
				for (int local_y = 0; local_y < size.y; local_y++)
				{
					for (int local_x = 0; local_x < size.x; local_x++)
					{
						int global_x = local_x + margin.x;
						int global_y = local_y + margin.y;
						parentbuf[global_y, global_x] = buf[local_y, local_x];
					}
				}
			}
		}
		public class PlayerRenderBox : RenderBox
		{

			public PlayerRenderBox(MyVector size) : base(size) { }
			public PlayerRenderBox(MyVector margin, MyVector size) : base(margin, size) { }
			public void Update(int maxhp, int hp)
			{
				DrawLife(maxhp, hp);
			}
			private void DrawSingleLife(int x, int y, bool isOn)
			{
				char[,] onLifeChar =
				{
					{'┏','┓'},
					{'┗','┛'},
				};
				char[,] offLifeChar =
				{
					{'┌','┐'},
					{'└','┘'},
				};
				if (isOn)
					for (int i = 0; i < 2; i++)
						for (int j = 0; j < 2; j++)
							buf[y + i, x + j] = onLifeChar[i, j];
				else
					for (int i = 0; i < 2; i++)
						for (int j = 0; j < 2; j++)
							buf[y + i, x + j] = offLifeChar[i, j];
			}
			private void DrawLife(int maxhp, int hp)
			{
				int lifePerLine = 4;
				int lifeLine = maxhp / lifePerLine + (maxhp % lifePerLine == 0 ? 0 : 1);
				int lifeImgSize = 2;
				HashSet<MyVector> lifePivots = new HashSet<MyVector>();
				for(int i = 0; i < maxhp; i++)
				{
					lifePivots.Add(new MyVector(
						(size.x / lifePerLine) * (i % lifePerLine) + (size.x / lifePerLine) / 2 - lifeImgSize / 2,
						((size.y / lifeLine) * (i / lifePerLine) + (size.y / lifeLine) / 2 - lifeImgSize / 2)/2)
					);
				}

				for (int r = 1; r < size.y; r++)
				{
					for (int c = 1; c < size.x; c++)
					{
						if (lifePivots.Contains(new MyVector(c, r)))
						{
							if(hp-- > 0)
								DrawSingleLife(c, r, true);
							else
								DrawSingleLife(c, r, false);
						}
					}
				}
			}
			public override void Init()
			{
				DrawBorder(" [You]");
			}
		}
		public class DungeonGame_Renderer
		{
			char[,] buf;

			private enum RenderIndex
			{
				Map,
				Balloon,
				Minimap,
				Player,
			};
			private RenderBox[] renderBoxs = new RenderBox[4];

			private MapRenderBox mapbox;
			private MsgRenderBox msgbox;
			private MinimapRenderBox minimapBox;
			private PlayerRenderBox playerbox;


			// ----- Singleton + Constructor
			private static DungeonGame_Renderer instance;
			private DungeonGame_Renderer(MyVector maxMapSize)
			{
				buf = new char[MAX_BUFFER_HEIGHT, MAX_BUFFER_WIDTH];

				MyVector margin;
				MyVector size;

				margin = new MyVector(2, 2);
				size = maxMapSize + new MyVector(2, 2);
				mapbox = new MapRenderBox(margin, size);
				renderBoxs[(int)RenderIndex.Map] = mapbox;

				margin = new MyVector(mapbox.Margin.x + mapbox.Size.x, mapbox.Margin.y);
				size = new MyVector((MAX_BUFFER_WIDTH - margin.x) / 4, 15);
				minimapBox = new MinimapRenderBox(margin, size);
				renderBoxs[(int)RenderIndex.Minimap] = minimapBox;

				margin = new MyVector(minimapBox.Margin.x + minimapBox.Size.x, minimapBox.Margin.y);
				size = new MyVector((MAX_BUFFER_WIDTH - margin.x) / 4, minimapBox.Size.y);
				playerbox = new PlayerRenderBox(margin, size);
				renderBoxs[(int)RenderIndex.Player] = playerbox;

				margin = new MyVector(playerbox.Margin.x + playerbox.Size.x, minimapBox.Margin.y);
				size = new MyVector(MAX_BUFFER_WIDTH - margin.x, minimapBox.Size.y);
				msgbox = new MsgRenderBox(margin, size);
				renderBoxs[(int)RenderIndex.Balloon] = msgbox;


				//margin = new MyVector(minimapBox.Margin.x, minimapBox.Margin.y + minimapBox.Size.y);
				//size = new MyVector(MAX_BUFFER_WIDTH - margin.x, MAX_BUFFER_HEIGHT - margin.y - 1);

			}
			public static DungeonGame_Renderer GetInstance(MyVector maxMapSize)
			{
				if (instance == null)
				{
					instance = new DungeonGame_Renderer(maxMapSize);
					for (int i = 0; i < MAX_BUFFER_HEIGHT; i++)
					{
						for (int j = 0; j < MAX_BUFFER_WIDTH; j++)
						{
							instance.buf[i, j] = EMPTY_SYMBOL;
						}
					}
				}

				return instance;
			}

			// ----- 
			public void Draw(DungeonGame_Map map, int stage_num, string msg, int maxhp, int hp)
			{
				mapbox.Update(map, stage_num);
				msgbox.Update(msg);
				minimapBox.Update(map);
				playerbox.Update(maxhp, hp);

				foreach (RenderBox box in renderBoxs)
					box.Render(buf);

				StringBuilder outbuf = new StringBuilder("");
				for (int i = 0; i < MAX_BUFFER_HEIGHT; i++)
				{
					for (int j = 0; j < MAX_BUFFER_WIDTH; j++)
					{
						outbuf.Append(buf[i, j]);
						buf[i, j] = EMPTY_SYMBOL;
					}
					outbuf.Append('\n');   // for windows
				}
				Console.SetCursorPosition(0, 0);
				Console.WriteLine(outbuf);
			}
			public void UpdateNewStage()
			{
				foreach (var box in renderBoxs)
					box.Init();
			}
		}

		// ------------- Entity
		public interface IEntity
		{
			void Init(MyVector pos);
			void Update();
			string OnPlayerEnter();
			public bool IsUpdatedOnCurFrame { get; set; }
		}
		public class EntityManager
		{
			private static EntityManager instance;
			private EntityManager() { }
			public static EntityManager GetInstance()
			{
				if (instance == null)
					instance = new EntityManager();
				return instance;
			}

			public Entity GetNewInstance<T>(MyVector pos) where T : Entity, new()
			{
				T entity = new T();
				entity.Init(pos);
				return entity;
			}
		}
		public abstract class Entity : IEntity, IRenderable
		{
			public char symbol;
			public MyVector pos = new MyVector();
			public static IMapDataModifier map;	// too many authority

			private bool isUpdatedOnCurFrame = false;
			public bool IsUpdatedOnCurFrame
			{
				get => isUpdatedOnCurFrame; set => isUpdatedOnCurFrame = value;
			}
			public virtual void Render(char[,] buf)
			{
				buf[pos.y, pos.x] = symbol;
			}
			public virtual void Init(MyVector pos) { this.pos = pos; }
			public virtual void Update() { isUpdatedOnCurFrame = true; }

			// Called when player moved to this Entity. This entity replaced to EmptyEntity. 
			protected Player MoveCapturing()
			{
				var mapdata = map.GetMapData();
				MyVector playerPos = new MyVector(mapdata["player_x"], mapdata["player_y"]);
				var player = (Player)map.GetEntity(playerPos.x, playerPos.y);
				MyVector tomove = pos;
				map.SetNewEntity<EmptyEntity>(tomove);
				map.Swap(playerPos, tomove);
				mapdata["player_x"] = tomove.x;
				mapdata["player_y"] = tomove.y;

				return player;
			}
			public abstract string OnPlayerEnter();
		}

		// ------------- Derives of Entity. Spawned by EntityManager. (except snake tails)
		public class Player : Entity
		{
			private int maxHp;
			private int hp;
			public int MaxHp { get => maxHp; }
			public int Hp { get => hp; }
			private bool isDead = false;
			public bool IsDead { get => isDead; }
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = 'P';
				maxHp = 8;
				hp = 3;
				isDead = false;
			}
			public void TakeDamage(int damage)
			{
				hp -= damage;
				if (hp > maxHp)
					hp = maxHp;
				if (hp <= 0)
					Die();
			}
			private void Die()
			{
				isDead = true;
			}
			public MyVector GetMove(char dir, MyVector mapSize)
			{
				MyVector tomove = new MyVector(pos.x + Utility.charToDeltaPos[dir].x, pos.y + Utility.charToDeltaPos[dir].y);
				if (mapSize.IsOutOfSquare(tomove))
				{
					tomove = pos;
				}

				return tomove;
			}
			public override string OnPlayerEnter()
			{
				return "Fail to move: out of map";
			}
		}
		public class EmptyEntity : Entity
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = EMPTY_SYMBOL;
			}
			public override string OnPlayerEnter()
			{
				Player player = MoveCapturing();
				return "You moved to (" + player.pos.x + ", " + player.pos.y + ")...";
			}
		}
		public class HealingPotion:Entity
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = '8';
			}
			public override string OnPlayerEnter()
			{
				Player player = MoveCapturing();

				int prevHp = player.Hp;
				player.TakeDamage(-1);
				int newHp = player.Hp;

				return $"You moved to ({player.pos.x}, {player.pos.y})...Got healing potion! Hp {prevHp} -> {newHp}";
			}
		}
		public class NextStageBicon: Entity
		{
			// bicon to go next stage if stage.clear 
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = '*';
			}
			public override string OnPlayerEnter()
			{
				return "You can't go next stage now!!";
			}
		}
		public class Monster : Entity
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = 'M';
			}
			public override string OnPlayerEnter()
			{
				Player player = MoveCapturing();

				var mapData = map.GetMapData();
				mapData[("monster_cnt")]--;
				if (mapData[("monster_cnt")] == 0)
				{
					return "You Killed Every Monster! Go Next Stage.";
				}
				return $"You moved to ({player.pos.x}, {player.pos.y})...Killed Monster! {mapData[("monster_cnt")]} monster left.";
			}
		}
		public class Snake_Head : Entity
		{
			protected List<Entity> bodies;
			int lifetime;
			int stuckedTurn;
			bool isBiconCreated;
			bool isTailCutted;
			float mapClearRate = 10f;
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				lifetime = 0;
				symbol = 'H';
				stuckedTurn = 0;
				isBiconCreated = false;
				isTailCutted = false;
				bodies = new List<Entity>() { this };
				AddTail();
				AddTail();
				AddTail();
			}
			protected void AddTail()
			{
				bodies.Add(EntityManager.GetInstance().GetNewInstance<Snake_Tail>(pos));
			}
			public override void Update()
			{
				base.Update();
				lifetime++;
				if (isBiconCreated == false)
				{
					if (lifetime > bodies.Count * 2)
					{
						if (rand.Next() % 100 < mapClearRate)
						{
							isBiconCreated = true;
							var lastTailPos = bodies[bodies.Count - 1].pos;
							map.SetNewEntity<MapClearBicon>(lastTailPos);
							bodies[bodies.Count - 1] = map.GetEntity(lastTailPos.x, lastTailPos.y);
						}
						else
							mapClearRate += 0.1f;
					}					
				}
				else if(isTailCutted == false)
				{
					var lastTailPos = bodies[bodies.Count - 1].pos;
					Entity lastTail = map.GetEntity(lastTailPos.x, lastTailPos.y);
					if (lastTail is not MapClearBicon)	// right after player got bicon. 
					{
						bodies.RemoveAt(bodies.Count - 1);
						isTailCutted = true;
					}
				}

				// get nearby pos
				List<MyVector> emptyPos = new List<MyVector>();
				(int, int)[] dirs = new (int, int)[4] { (pos.x + 1, pos.y), (pos.x - 1, pos.y), (pos.x, pos.y + 1), (pos.x, pos.y - 1) };

				for (int i = 0; i < 4; i++)
				{
					int x = dirs[i].Item1;
					int y = dirs[i].Item2;
					if (map.GetSize().IsOutOfSquare(new MyVector(x, y)) == false)
					{
						if (map.GetEntity(x, y) is EmptyEntity)
							emptyPos.Add(new MyVector(x, y));


					}
				}

				// get random nearby empty pos
				if (emptyPos.Count == 0)
				{
					if (++stuckedTurn >= 5)
					{
						map.Swap(bodies[bodies.Count - 1].pos, bodies[0].pos);
						for(int i = 0; i < bodies.Count - 1; i++)
							map.Swap(bodies[i].pos, bodies[i+1].pos);
					}
					return;
				}
				else
					stuckedTurn = 0;

				var moveto = emptyPos[rand.Next() % emptyPos.Count];

				// move head, and all tails
				MyVector[] originPos = new MyVector[bodies.Count];
				for (int i = 0; i < bodies.Count; i++)
				{
					originPos[i] = bodies[i].pos;
				}

				// head move
				map.Swap(pos, moveto);
				// tail move
				for (int i = 1; i < bodies.Count; i++)
				{
					if (map.GetEntity(bodies[i].pos.x, bodies[i].pos.y) is EmptyEntity)
					{
						map.SetEntity(bodies[i], bodies[i].pos);
					}
					map.Swap(bodies[i].pos, originPos[i - 1]);
					bodies[i].pos = originPos[i - 1];
				}
			}
			public override string OnPlayerEnter()
			{
				var player = (Player)map.GetEntity(map.GetMapData()["player_x"], map.GetMapData()["player_y"]);
				player.TakeDamage(1);

				return $"You Tried to dive Strong Monster! Life : {player.Hp}. Never Do that!!!";
			}
		}
		public class Snake_Tail : Entity
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = 'O';
			}
			public override string OnPlayerEnter()
			{
				var player = (Player)map.GetEntity(map.GetMapData()["player_x"], map.GetMapData()["player_y"]);
				player.TakeDamage(1);

				return $"You Tried to dive Strong Monster! Life : {player.Hp}. Never Do that!!!";
			}
		}
		public class BigSnake_Head: Snake_Head
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);

				AddTail();
				AddTail();
				AddTail();
				AddTail();
			}
		}
		public class MapClearBicon: Entity
		{
			// bicon to clear map
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = '*';
			}
			public override string OnPlayerEnter()
			{
				_ = MoveCapturing();
				map.SetClear(true);
				return "Map Clear, door Opened!!!";
			}
		}
		public class SnakeBaby : Entity
		{
			private int turnToGrow;
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = 'M';
				turnToGrow = rand.Next() % 20 + 20;
			}
			public override void Update()
			{
				base.Update();
				if(turnToGrow < 5)
				{
					symbol = 'H';
				}
				if(--turnToGrow <= 0)
				{
					map.SetNewEntity<Snake_Head>(pos);
					map.GetEntity(pos.x, pos.y).IsUpdatedOnCurFrame = true;
					return;
				}
			}
			public override string OnPlayerEnter()
			{
				Player player = MoveCapturing();
				return $"You moved to ({player.pos.x}, {player.pos.y})...Eliminated Snake Egg! It was about to grow up after {turnToGrow} Turn(s).";
			}
		}
		public class Door : Entity
		{
			private DungeonGame_Map targetMap;
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = 'D';
			}
			public void ConnectTo(DungeonGame_Map map)
			{
				this.targetMap = map;
			}
			public DungeonGame_Map GetTargetMap()
			{
				return targetMap;
			}
			public override string OnPlayerEnter()
			{
				return "Door Locked!";
			}
		}
		public class Fence : Entity
		{
			public override void Init(MyVector pos)
			{
				base.Init(pos);
				symbol = FENCE_SYMBOL;
			}
			public override string OnPlayerEnter()
			{
				return "Fail to move: conflicts wall";
			}
		}

		// ------------- Utility Static Class
		public static class Utility
		{
			private static HashSet<char> ableChars = new HashSet<char> { 'W', 'A', 'S', 'D', 'Q'};
			public static Dictionary<DirIndex, MyVector> dirToDeltaPos = new Dictionary<DirIndex, MyVector>
			{
				{DirIndex.Left, new MyVector(-1, 0)},
				{DirIndex.Right, new MyVector(1, 0)},
				{DirIndex.Up, new MyVector(0, -1)},
				{DirIndex.Down, new MyVector(0, 1)},
			};
			public static Dictionary<char, MyVector> charToDeltaPos = new Dictionary<char, MyVector>() {
				{ 'A', new MyVector(-1, 0) },
				{ 'D', new MyVector(1, 0) },
				{ 'W', new MyVector(0, -1) },
				{ 'S', new MyVector(0, 1) },
			};
			public static Dictionary<char, DirIndex> charToDirIndex = new Dictionary<char, DirIndex>()
			{
				{ 'A', DirIndex.Left},
				{ 'D', DirIndex.Right},
				{ 'W', DirIndex.Up},
				{ 'S', DirIndex.Down},
			};
			public static Dictionary<int, DirIndex> intToDirIndex = new Dictionary<int, DirIndex>()
			{
				{(int)DirIndex.Left, DirIndex.Left},
				{(int)DirIndex.Right, DirIndex.Right},
				{(int)DirIndex.Up, DirIndex.Up},
				{(int)DirIndex.Down, DirIndex.Down},
			};
			public static char InputSingleChar()
			{
				char c;
				string input_announcement = "[W / A / S / D / Q to quit]: ";
				Console.Write(input_announcement);
				do
				{
					c = Console.ReadKey(true).KeyChar;
					c = char.ToUpper(c);
				} while (ableChars.Contains(c) == false);

				return c;
			}
		}


		// ------------- Main
		static void Main(string[] args)
		{
			Console.CursorVisible = false;
			Console.SetWindowSize(MAX_BUFFER_WIDTH + 2, MAX_BUFFER_HEIGHT + 2);
			DungeonGame game = DungeonGame.GetInstance();
			game.Play();

			return;
		}
	}
}
